import { Link } from 'react-router-dom';
import { MessageSquare, RefreshCw } from 'lucide-react';
import { MhdBadge } from '@/components/ui/MhdBadge';
import { MhdCard } from '@/components/ui/MhdCard';
import { MhdEmptyState } from '@/components/ui/MhdEmptyState';
import { MhdPageHeader } from '@/components/ui/MhdPageHeader';
import { mhdPaginationSummary, MhdPaginationControls, useMhdPagination } from '@/components/ui/MhdPagination';
import { MhdTable, MhdTableFooter, MhdTd, MhdTh, MhdTr } from '@/components/ui/MhdTable';
import { useMhdNotifications } from '@/features/notifications/Hook';
import { MHD_NOTIFICATION_TYPE_LABELS } from '@/features/notifications/Types';
import { useMhdMessageThreads } from '@/features/messaging/Hook';
import { MhdCommunicationsTabs } from '@/appshell/components/MhdCommunicationsTabs';
import { buttonBaseClasses, buttonVariantClasses } from '@/components/ui/buttonStyles';
import { cn } from '@/utils/cn';

function formatDate(value: string) {
  return new Date(value).toLocaleString();
}

function formatWhen(value: string | null) {
  if (!value) return 'No messages';
  return new Intl.DateTimeFormat(undefined, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(value));
}

export function MhdCommunicationsPage() {
  const { notifications, unreadCount, isLoading, error, markAllRead, refetch } =
    useMhdNotifications();
  const notificationsPagination = useMhdPagination(notifications.length, {
    resetKey: `${notifications.length}:${notifications[0]?.id ?? ''}`,
  });
  const systemAlerts = notifications.filter(
    (notification) => notification.notificationType === 'SYSTEM',
  );
  const messagesQuery = useMhdMessageThreads({ limit: 5 });
  const recentThreads = messagesQuery.data ?? [];
  const unreadMessageCount = recentThreads.reduce((sum, thread) => sum + thread.unreadCount, 0);

  return (
    <div className="space-y-6">
      <MhdPageHeader
        title="Communications"
        description="Central hub for user messaging, system alerts, and notifications generated by other modules."
        actions={
          <>
            <button
              type="button"
              onClick={refetch}
              className={cn(buttonBaseClasses, buttonVariantClasses.secondary, 'gap-1.5')}
            >
              <RefreshCw className="h-4 w-4" aria-hidden />
              Refresh
            </button>
            <button
              type="button"
              onClick={markAllRead}
              disabled={unreadCount === 0}
              className={cn(buttonBaseClasses, buttonVariantClasses.primary)}
            >
              Mark All Read
            </button>
          </>
        }
      />

      <MhdCommunicationsTabs active="overview" />

      <div className="grid gap-4 md:grid-cols-3">
        <Link to="/communications/messaging">
          <MhdCard className="p-5 transition-colors hover:border-accent">
            <p className="text-xs font-semibold uppercase tracking-wide text-accent">Messages</p>
            <p className="mt-2 text-3xl font-bold text-foreground">{recentThreads.length}</p>
            <p className="mt-1 text-sm text-muted-foreground">{unreadMessageCount} Unread</p>
          </MhdCard>
        </Link>
        <MhdCard className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-accent">Notifications</p>
          <p className="mt-2 text-3xl font-bold text-foreground">{notifications.length}</p>
          <p className="mt-1 text-sm text-muted-foreground">{unreadCount} Unread</p>
        </MhdCard>
        <MhdCard className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-accent">System Alerts</p>
          <p className="mt-2 text-3xl font-bold text-foreground">{systemAlerts.length}</p>
          <p className="mt-1 text-sm text-muted-foreground">Generated By Platform Modules</p>
        </MhdCard>
      </div>

      {error ? (
        <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
          {error}
        </p>
      ) : null}

      <MhdCard className="overflow-hidden p-0">
        <div className="flex items-center justify-between border-b border-border p-4">
          <h2 className="text-sm font-semibold text-foreground">Recent Messages</h2>
          <Link
            to="/communications/messaging"
            className="text-sm font-semibold text-accent hover:text-accent-hover"
          >
            Open Inbox
          </Link>
        </div>
        {messagesQuery.isLoading ? (
          <p className="p-4 text-sm text-muted-foreground">Loading messages…</p>
        ) : recentThreads.length === 0 ? (
          <MhdEmptyState
            icon={MessageSquare}
            title="No conversations yet"
            description="Start a direct message with another user from the Messaging tab."
            className="px-4 py-6"
          />
        ) : (
          <div className="divide-y divide-border">
            {recentThreads.map((thread) => (
              <Link
                key={thread.id}
                to="/communications/messaging"
                className="grid gap-1 px-4 py-3 transition-colors hover:bg-slate-50"
              >
                <span className="flex min-w-0 items-center justify-between gap-3">
                  <span className="truncate text-sm font-semibold text-foreground">
                    {thread.subject || thread.lastMessageBody || 'Direct message'}
                  </span>
                  {thread.unreadCount > 0 && (
                    <MhdBadge variant="accent" className="shrink-0">
                      {thread.unreadCount}
                    </MhdBadge>
                  )}
                </span>
                <span className="line-clamp-1 text-xs text-muted-foreground">
                  {thread.lastMessageBody ?? 'No messages yet'}
                </span>
                <span className="text-[11px] text-muted-foreground">
                  {formatWhen(thread.lastMessageAt)}
                </span>
              </Link>
            ))}
          </div>
        )}
      </MhdCard>

      <MhdCard className="overflow-hidden p-0">
        <div className="border-b border-border p-4">
          <h2 className="text-sm font-semibold text-foreground">Recent Notifications</h2>
        </div>
        <MhdTable>
          <thead>
            <tr>
              <MhdTh>Notification</MhdTh>
              <MhdTh>Type</MhdTh>
              <MhdTh>Status</MhdTh>
              <MhdTh>Created</MhdTh>
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              <MhdTr>
                <MhdTd colSpan={4} className="text-center text-muted-foreground">
                  Loading Communications…
                </MhdTd>
              </MhdTr>
            ) : notifications.length === 0 ? (
              <MhdTr>
                <MhdTd colSpan={4} className="text-center text-muted-foreground">
                  No Communications Found.
                </MhdTd>
              </MhdTr>
            ) : (
              notificationsPagination.sliceItems(notifications).map((notification) => (
                <MhdTr key={notification.id}>
                  <MhdTd>
                    <p className="font-semibold text-foreground">{notification.title}</p>
                    {notification.body ? (
                      <p className="mt-1 text-sm text-muted-foreground">{notification.body}</p>
                    ) : null}
                  </MhdTd>
                  <MhdTd>{MHD_NOTIFICATION_TYPE_LABELS[notification.notificationType]}</MhdTd>
                  <MhdTd>{notification.isRead ? 'Read' : 'Unread'}</MhdTd>
                  <MhdTd className="whitespace-nowrap text-muted-foreground">
                    {formatDate(notification.createdAt)}
                  </MhdTd>
                </MhdTr>
              ))
            )}
          </tbody>
        </MhdTable>
        <MhdTableFooter
          summary={mhdPaginationSummary(notificationsPagination, notifications.length, 'Communications')}
        >
          <MhdPaginationControls pagination={notificationsPagination} />
        </MhdTableFooter>
      </MhdCard>
    </div>
  );
}
