import { RefreshCw } from 'lucide-react';
import { MhdCard } from '@/components/ui/MhdCard';
import { MhdPageHeader } from '@/components/ui/MhdPageHeader';
import { MhdTable, MhdTableFooter, MhdTd, MhdTh, MhdTr } from '@/components/ui/MhdTable';
import { useMhdNotifications } from '@/features/notifications/Hook';
import { MHD_NOTIFICATION_TYPE_LABELS } from '@/features/notifications/Types';
import { MhdCommunicationsTabs } from '@/appshell/components/MhdCommunicationsTabs';
import { buttonBaseClasses, buttonVariantClasses } from '@/components/ui/Button';
import { cn } from '@/utils/cn';

function formatDate(value: string) {
  return new Date(value).toLocaleString();
}

export function MhdCommunicationsPage() {
  const { notifications, unreadCount, isLoading, error, markAllRead, refetch } =
    useMhdNotifications();
  const systemAlerts = notifications.filter(
    (notification) => notification.notificationType === 'SYSTEM',
  );

  return (
    <div className="space-y-6">
      <MhdPageHeader
        title="Communications"
        description="Central hub for user messaging, system alerts, and notifications generated by other modules."
        actions={
          <>
            <button
              type="button"
              onClick={refetch}
              className={cn(buttonBaseClasses, buttonVariantClasses.secondary, 'gap-1.5')}
            >
              <RefreshCw className="h-4 w-4" aria-hidden />
              Refresh
            </button>
            <button
              type="button"
              onClick={markAllRead}
              disabled={unreadCount === 0}
              className={cn(buttonBaseClasses, buttonVariantClasses.primary)}
            >
              Mark All Read
            </button>
          </>
        }
      />

      <MhdCommunicationsTabs active="overview" />

      <div className="grid gap-4 md:grid-cols-2">
        <MhdCard className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-accent">Notifications</p>
          <p className="mt-2 text-3xl font-bold text-foreground">{notifications.length}</p>
          <p className="mt-1 text-sm text-muted-foreground">{unreadCount} Unread</p>
        </MhdCard>
        <MhdCard className="p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-accent">System Alerts</p>
          <p className="mt-2 text-3xl font-bold text-foreground">{systemAlerts.length}</p>
          <p className="mt-1 text-sm text-muted-foreground">Generated By Platform Modules</p>
        </MhdCard>
      </div>

      {error ? (
        <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
          {error}
        </p>
      ) : null}

      <MhdCard className="overflow-hidden p-0">
        <MhdTable>
          <thead>
            <tr>
              <MhdTh>Notification</MhdTh>
              <MhdTh>Type</MhdTh>
              <MhdTh>Status</MhdTh>
              <MhdTh>Created</MhdTh>
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              <MhdTr>
                <MhdTd colSpan={4} className="text-center text-muted-foreground">
                  Loading Communications…
                </MhdTd>
              </MhdTr>
            ) : notifications.length === 0 ? (
              <MhdTr>
                <MhdTd colSpan={4} className="text-center text-muted-foreground">
                  No Communications Found.
                </MhdTd>
              </MhdTr>
            ) : (
              notifications.map((notification) => (
                <MhdTr key={notification.id}>
                  <MhdTd>
                    <p className="font-semibold text-foreground">{notification.title}</p>
                    {notification.body ? (
                      <p className="mt-1 text-sm text-muted-foreground">{notification.body}</p>
                    ) : null}
                  </MhdTd>
                  <MhdTd>{MHD_NOTIFICATION_TYPE_LABELS[notification.notificationType]}</MhdTd>
                  <MhdTd>{notification.isRead ? 'Read' : 'Unread'}</MhdTd>
                  <MhdTd className="whitespace-nowrap text-muted-foreground">
                    {formatDate(notification.createdAt)}
                  </MhdTd>
                </MhdTr>
              ))
            )}
          </tbody>
        </MhdTable>
        <MhdTableFooter
          summary={`Showing ${notifications.length === 0 ? 0 : 1} To ${notifications.length} Of ${
            notifications.length
          } Communications`}
        />
      </MhdCard>
    </div>
  );
}
