import { Link } from 'react-router-dom';
import { Bell, RefreshCw } from 'lucide-react';
import { MhdCard } from '@/components/ui/MhdCard';
import { MhdPageHeader } from '@/components/ui/MhdPageHeader';
import { MhdTable, MhdTableFooter, MhdTd, MhdTh, MhdTr } from '@/components/ui/MhdTable';
import { useMhdNotifications } from '@/features/notifications/Hook';
import { MhdCommunicationsTabs } from '@/appshell/components/MhdCommunicationsTabs';
import { buttonBaseClasses, buttonVariantClasses } from '@/components/ui/Button';
import { cn } from '@/utils/cn';

function formatDate(value: string) {
  return new Date(value).toLocaleString();
}

export function MhdSystemAlertsPage() {
  const { notifications, isLoading, error, refetch } = useMhdNotifications();
  const alerts = notifications.filter((notification) => notification.notificationType === 'SYSTEM');

  return (
    <div className="space-y-6">
      <MhdPageHeader
        title="System Alerts"
        description="System-level alerts generated by MyHRDepot modules."
        backTo="/communications"
        backLabel="Communications"
        actions={
          <button
            type="button"
            onClick={refetch}
            className={cn(buttonBaseClasses, buttonVariantClasses.primary, 'gap-1.5')}
          >
            <RefreshCw className="h-4 w-4" aria-hidden />
            Refresh Alerts
          </button>
        }
      />

      <MhdCommunicationsTabs active="system-alerts" />

      {error ? (
        <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
          {error}
        </p>
      ) : null}

      <MhdCard className="overflow-hidden p-0">
        <MhdTable>
          <thead>
            <tr>
              <MhdTh>Alert</MhdTh>
              <MhdTh>Entity</MhdTh>
              <MhdTh>Status</MhdTh>
              <MhdTh>Created</MhdTh>
              <MhdTh>Action</MhdTh>
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              <MhdTr>
                <MhdTd colSpan={5} className="text-center text-muted-foreground">
                  Loading System Alerts…
                </MhdTd>
              </MhdTr>
            ) : alerts.length === 0 ? (
              <MhdTr>
                <MhdTd colSpan={5} className="text-center text-muted-foreground">
                  <div className="flex flex-col items-center gap-2 py-8">
                    <Bell className="h-6 w-6 text-accent" aria-hidden />
                    <span>No System Alerts Found.</span>
                  </div>
                </MhdTd>
              </MhdTr>
            ) : (
              alerts.map((alert) => (
                <MhdTr key={alert.id}>
                  <MhdTd>
                    <p className="font-semibold text-foreground">{alert.title}</p>
                    {alert.body ? (
                      <p className="mt-1 text-sm text-muted-foreground">{alert.body}</p>
                    ) : null}
                  </MhdTd>
                  <MhdTd>{alert.entityType ?? 'System'}</MhdTd>
                  <MhdTd>{alert.isRead ? 'Read' : 'Unread'}</MhdTd>
                  <MhdTd className="whitespace-nowrap text-muted-foreground">
                    {formatDate(alert.createdAt)}
                  </MhdTd>
                  <MhdTd>
                    {alert.actionUrl ? (
                      <Link
                        to={alert.actionUrl}
                        className="font-semibold text-accent hover:text-accent-hover"
                      >
                        Open
                      </Link>
                    ) : (
                      <span className="text-muted-foreground">—</span>
                    )}
                  </MhdTd>
                </MhdTr>
              ))
            )}
          </tbody>
        </MhdTable>
        <MhdTableFooter
          summary={`Showing ${alerts.length === 0 ? 0 : 1} To ${alerts.length} Of ${
            alerts.length
          } System Alerts`}
        />
      </MhdCard>
    </div>
  );
}
