import type { MhdOnboardingDocumentKey, MhdOnboardingPacketDefinition } from './Types';

export const MHD_ONBOARDING_PACKET_DEFINITIONS: MhdOnboardingPacketDefinition[] = [
  {
    documentKey: 'onboarding_direct_deposits',
    label: 'Direct Deposit',
    formName: 'New Hire - Direct Deposit',
    accessTier: 'Restricted',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Banking setup for payroll deposits.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_employment_applications',
    label: 'Employment Application',
    formName: 'New Hire - Employment Application',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Structured employment application intake.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_w4_elections',
    label: 'W-4 Election',
    formName: 'New Hire - W-4 Election',
    accessTier: 'Restricted',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Federal withholding election.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_emergency_contacts',
    label: 'Emergency Contact',
    formName: 'New Hire - Emergency Contact',
    accessTier: 'Standard',
    requiresSignature: false,
    generatedDocumentRequired: false,
    description: 'Emergency contact information for the employee.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_i9_records',
    label: 'Form I-9',
    formName: 'New Hire - I-9',
    accessTier: 'Restricted',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Employment eligibility verification.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_candidate_evaluations',
    label: 'Candidate Evaluation',
    formName: 'New Hire - Candidate Evaluation',
    accessTier: 'Standard',
    requiresSignature: false,
    generatedDocumentRequired: false,
    description: 'Internal interviewer evaluation.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_offer_letters',
    label: 'Offer Letter',
    formName: 'New Hire - Offer Letter',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Offer terms accepted by the employee.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_consumer_report_disclosures',
    label: 'Consumer Report Disclosure',
    formName: 'New Hire - Consumer Report Disclosure',
    accessTier: 'Restricted',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Background check disclosure and authorization.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_harassment_policy_acks',
    label: 'Harassment Policy',
    formName: 'New Hire - Harassment Policy Acknowledgment',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Acknowledgment of harassment policy.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_time_of_hire_pamphlet_acks',
    label: 'Time of Hire Pamphlet',
    formName: 'New Hire - Time of Hire Pamphlet',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Acknowledgment of required time-of-hire pamphlet.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_wage_notice_acks',
    label: 'Wage Notice',
    formName: 'New Hire - Wage Notice',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Wage notice acknowledgment.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_health_marketplace_notice_acks',
    label: 'Health Marketplace Notice',
    formName: 'New Hire - Health Marketplace Notice',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Marketplace notice acknowledgment with variant selection.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_wotc_8850_forms',
    label: 'WOTC Form 8850',
    formName: 'New Hire - WOTC Form 8850',
    accessTier: 'Restricted',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Work Opportunity Tax Credit 8850.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_meal_waiver_acks',
    label: 'Meal Waiver',
    formName: 'New Hire - Meal Waiver',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Meal waiver acknowledgment.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_badge_acknowledgments',
    label: 'Badge Acknowledgment',
    formName: 'New Hire - Badge Acknowledgment',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Badge issuance acknowledgment.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_wotc_9061_forms',
    label: 'WOTC Form 9061',
    formName: 'New Hire - WOTC Form 9061',
    accessTier: 'Restricted',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Work Opportunity Tax Credit 9061.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_self_identification_forms',
    label: 'Voluntary Self-Identification',
    formName: 'New Hire - Voluntary Self-Identification',
    accessTier: 'Restricted',
    requiresSignature: false,
    generatedDocumentRequired: false,
    description: 'Voluntary self-identification and EEO data collection.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_dispute_resolution_acks',
    label: 'Dispute Resolution Policy',
    formName: 'New Hire - Dispute Resolution Policy',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Dispute resolution acknowledgment.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_handbook_acknowledgments',
    label: 'Handbook Acknowledgment',
    formName: 'New Hire - Handbook Acknowledgment',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Employee handbook acknowledgment.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_required_notices_acks',
    label: 'Required Notices',
    formName: 'New Hire - Required Notices',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Acknowledgment of bundled required notices.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_surveillance_policy_acks',
    label: 'Surveillance Policy',
    formName: 'New Hire - Surveillance Policy',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'Surveillance policy acknowledgment.',
    isRequiredByDefault: true,
  },
  {
    documentKey: 'onboarding_at_will_acknowledgments',
    label: 'At-Will Acknowledgment',
    formName: 'New Hire - At-Will Acknowledgment',
    accessTier: 'Standard',
    requiresSignature: true,
    generatedDocumentRequired: true,
    description: 'At-will employment acknowledgment.',
    isRequiredByDefault: true,
  },
];

export const MHD_ONBOARDING_PACKET_BY_KEY: Record<MhdOnboardingDocumentKey, MhdOnboardingPacketDefinition> =
  Object.fromEntries(
    MHD_ONBOARDING_PACKET_DEFINITIONS.map((item) => [item.documentKey, item]),
  ) as Record<MhdOnboardingDocumentKey, MhdOnboardingPacketDefinition>;
